name: poly_bool_dart
description: Boolean operations on polygons (union, intersection, difference, xor) (this library is a port for flutter of polybooljs.
version: 0.1.0
homepage: https://github.com/mohammedX6/poly_bool_dart/tree/master

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dart_jts: ^0.2.1
  quiver: ^3.0.1+1
  latlong2: ^0.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
